version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./todo:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./todo:/var/www/html
    depends_on:
      - app
networks:
  laravel:
